server:
  port: 8888 # Default port

spring:
  application:
    name: config-server
  profiles:
    active: native # Thư mục local để lưu cấu hình các service khác
  cloud:
    config:
      server:
        native:
          # Chỉ định nơi chứa file cấu hình của các service (nằm trong resource)
          search-locations: classpath:/config